# Generated by Django 3.0.8 on 2020-07-29 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='거래처 이름')),
                ('phone', models.PositiveIntegerField(verbose_name='거래처 번호')),
                ('address', models.TextField(verbose_name='거래처 주소')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='제품 이름')),
                ('image', models.ImageField(upload_to='shop/photo/', verbose_name='제품 사진')),
                ('content', models.TextField(verbose_name='제품 상세 설명')),
                ('price', models.PositiveIntegerField(verbose_name='제품 가격')),
                ('amount', models.PositiveIntegerField(verbose_name='제품 수량')),
                ('account', models.ForeignKey(db_column='name', on_delete=django.db.models.deletion.CASCADE, to='shop.Account', verbose_name='거래처')),
            ],
        ),
    ]
